import { useEffect, useState } from "react";
import OfficialShell from "../components/OfficialShell";
import { api, unwrap } from "../api/client";

const downloadBlob = (response, name) => { const url=URL.createObjectURL(response.data); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),500); };

export default function RegistrationsByUsers(){
  const [roles,setRoles]=useState([]),[roleId,setRoleId]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[data,setData]=useState({stats:{MB:{},HS100:{}},rows:[]}),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{api.get("/report-dashboards/registrations-by-users").then(r=>setRoles((unwrap(r)||{}).roles||[])).catch(e=>setError(e.response?.data?.message||"Unable to load roles."));},[]);
  const query=()=>{const p=new URLSearchParams();if(roleId)p.set("roleId",roleId);if(startDate)p.set("startDate",startDate);if(endDate)p.set("endDate",endDate);return p.toString()};
  const submit=async()=>{setLoading(true);setError("");try{setData(unwrap(await api.get(`/report-dashboards/registrations-by-users?${query()}`))||data);}catch(e){setError(e.response?.data?.message||"Unable to load dashboard.")}finally{setLoading(false)}};
  const exportIt=async(type="xlsx")=>{if(!roleId)return;try{const r=await api.get(`/report-dashboards/registrations-by-users/export?${query()}${type?`&format=${type}`:""}`,{responseType:"blob"});downloadBlob(r,`registrations-by-users.${type}`)}catch(e){setError(e.response?.data?.message||"Unable to export.")}};
  const card=(label,s)=><div className="report-stat-card"><span>{label}</span><strong>{s.total||0}</strong><div><small>Self Registration: {s.self||0}</small><small>User Registrations: {s.user||0}</small><small>Total Verification: {s.verified||0}</small><small>Total Pending: {s.pending||0}</small></div></div>;
  return <OfficialShell><section className="report-dashboard"><div className="workspace-title"><div><div className="eyebrow">DASHBOARD</div><h1>Registrations By Users</h1><p>Track registrations created by authorised users.</p></div></div><div className="report-filter panel"><label className="field"><span>Role *</span><select value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select Role</option>{roles.filter(r=>r.code!=="ADMIN").map(r=><option key={r._id} value={r._id}>{r.name} · {r.code}</option>)}</select></label><label className="field"><span>Start Date</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="field"><span>End Date</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button className="primary" onClick={submit} disabled={loading}>{loading?"Loading…":"Submit"}</button><button className="secondary" onClick={()=>exportIt("xlsx")} disabled={!roleId}>Export Excel</button><button className="secondary" onClick={()=>exportIt("pdf")} disabled={!roleId}>Export PDF</button></div>{error&&<div className="error">{error}</div>}<div className="report-stat-grid">{card("MB STATS",data.stats.MB||{})}{card("HS100 STATS",data.stats.HS100||{})}</div>{!roleId?<div className="panel report-empty">Select a role and click Submit to view the user table.</div>:<div className="table-wrap"><table><thead><tr><th>#</th><th>UserName</th><th>Districts</th><th>Blocks</th><th>MB</th><th>HS100</th><th>Count</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.UserName+r.Contact}><td>{r["#"]}</td><td>{r.UserName}</td><td>{r.Districts||"-"}</td><td>{r.Blocks||"-"}</td><td>{r.MB}</td><td>{r.HS100}</td><td><strong>{r.Count}</strong></td></tr>)}{!data.rows.length&&<tr><td colSpan="7" className="empty-row">No users/registrations found.</td></tr>}</tbody></table></div>}</section></OfficialShell>;
}
