import { useEffect, useState } from "react";
import OfficialShell from "../components/OfficialShell";
import { api, unwrap } from "../api/client";
const downloadBlob=(r,n)=>{const u=URL.createObjectURL(r.data),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
export default function SchoolVisitDashboard(){
 const [roles,setRoles]=useState([]),[districts,setDistricts]=useState([]),[blocks,setBlocks]=useState([]),[filters,setFilters]=useState({roleId:"",startDate:"",endDate:"",districtId:"",blockId:"",search:""}),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api.get("/report-dashboards/school-visits"),api.get("/regions/districts")]).then(([r,d])=>{setRoles((unwrap(r)||{}).roles||[]);setDistricts(unwrap(d)||[])}).catch(e=>setError(e.response?.data?.message||"Unable to load filters."))},[]);
 useEffect(()=>{if(!filters.districtId){setBlocks([]);return}api.get(`/regions/blocks?districtId=${filters.districtId}`).then(r=>setBlocks(unwrap(r)||[])).catch(()=>setBlocks([]))},[filters.districtId]);
 const query=(extra={})=>{const p=new URLSearchParams();Object.entries({...filters,...extra}).forEach(([k,v])=>{if(v)p.set(k,v)});return p.toString()};
 const submit=async()=>{setLoading(true);setError("");try{setRows((unwrap(await api.get(`/report-dashboards/school-visits?${query()}`))||{}).rows||[])}catch(e){setError(e.response?.data?.message||"Unable to load dashboard.")}finally{setLoading(false)}};
 const exportIt=async(full=false)=>{try{const q=query(full?{fullDetails:"1"}:{});const r=await api.get(`/report-dashboards/school-visits/export?${q}`,{responseType:"blob"});downloadBlob(r,full?"school-visit-full-details.xlsx":"school-visit-summary.xlsx")}catch(e){setError(e.response?.data?.message||"Unable to export.")}};
 const exportUser=async(userId)=>{try{const r=await api.get(`/report-dashboards/school-visits/export?${query({userId,fullDetails:"1"})}`,{responseType:"blob"});downloadBlob(r,`school-visit-${userId}.xlsx`)}catch(e){setError(e.response?.data?.message||"Unable to export user report.")}};
 return <OfficialShell><section className="report-dashboard"><div className="workspace-title"><div><div className="eyebrow">DASHBOARD</div><h1>School Visit Dashboard</h1><p>Track all users who have School Visit access and their visit activity.</p></div></div><div className="report-filter panel"><label className="field"><span>Role</span><select value={filters.roleId} onChange={e=>setFilters({...filters,roleId:e.target.value})}><option value="">All Roles</option>{roles.filter(r=>r.code!=="ADMIN").map(r=><option key={r._id} value={r._id}>{r.name} · {r.code}</option>)}</select></label><label className="field"><span>Start Date</span><input type="date" value={filters.startDate} onChange={e=>setFilters({...filters,startDate:e.target.value})}/></label><label className="field"><span>End Date</span><input type="date" value={filters.endDate} onChange={e=>setFilters({...filters,endDate:e.target.value})}/></label><label className="field"><span>District</span><select value={filters.districtId} onChange={e=>setFilters({...filters,districtId:e.target.value,blockId:""})}><option value="">All Districts</option>{districts.map(d=><option key={d._id} value={d._id}>{d.districtName}</option>)}</select></label><label className="field"><span>Block</span><select value={filters.blockId} disabled={!filters.districtId} onChange={e=>setFilters({...filters,blockId:e.target.value})}><option value="">All Blocks</option>{blocks.map(b=><option key={b._id} value={b._id}>{b.blockName}</option>)}</select></label><label className="field"><span>Name / Role / Contact</span><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Regex-style search"/></label><button className="primary" onClick={submit} disabled={loading}>{loading?"Loading…":"Submit"}</button><button className="secondary" onClick={()=>exportIt(false)}>Export Excel</button><button className="secondary" onClick={()=>exportIt(true)}>Export Full Details</button></div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>UserName</th><th>Contact</th><th>Visits Created</th><th>Visited</th><th>Pending</th><th>PDFUploaded</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r["_userId"]}><td>{r.UserName}</td><td>{r.Contact}</td><td>{r["Visits Created"]}</td><td>{r.Visited}</td><td>{r.Pending}</td><td>{r.PDFUploaded}</td><td><button className="secondary" onClick={()=>exportUser(r["_userId"])}>Export Report</button></td></tr>)}{!rows.length&&!loading&&<tr><td colSpan="7" className="empty-row">No School Visit access users found.</td></tr>}</tbody></table></div></section></OfficialShell>;
}
