import { useEffect, useState } from "react";
import OfficialShell from "../components/OfficialShell";
import { api, unwrap } from "../api/client";
const downloadBlob=(r,n)=>{const u=URL.createObjectURL(r.data),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
export default function VerificationByUsers(){
 const [search,setSearch]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const query=()=>{const p=new URLSearchParams();if(search)p.set("search",search);if(startDate)p.set("startDate",startDate);if(endDate)p.set("endDate",endDate);return p.toString()};
 const submit=async()=>{setLoading(true);setError("");try{setRows((unwrap(await api.get(`/report-dashboards/verification-by-users?${query()}`))||{}).rows||[])}catch(e){setError(e.response?.data?.message||"Unable to load dashboard.")}finally{setLoading(false)}};
 useEffect(()=>{submit()},[]);
 const exportIt=async(format)=>{try{const r=await api.get(`/report-dashboards/verification-by-users/export?${query()}&format=${format}`,{responseType:"blob"});downloadBlob(r,`verification-by-users.${format}`)}catch(e){setError(e.response?.data?.message||"Unable to export.")}};
 return <OfficialShell><section className="report-dashboard"><div className="workspace-title"><div><div className="eyebrow">DASHBOARD</div><h1>Verification By Users</h1><p>Track verification workload and completed verification status.</p></div></div><div className="report-filter panel"><label className="field"><span>Search Name / Contact</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Regex-style search"/></label><label className="field"><span>Start Date</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="field"><span>End Date</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button className="primary" onClick={submit} disabled={loading}>{loading?"Loading…":"Submit"}</button><button className="secondary" onClick={()=>exportIt("xlsx")}>Export Excel</button><button className="secondary" onClick={()=>exportIt("pdf")}>Export PDF</button></div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>UserName</th><th>Districts</th><th>Pending MB</th><th>Verified MB</th><th>Rejected MB</th><th>Pending HS100</th><th>Verified HS100</th><th>Rejected HS100</th></tr></thead><tbody>{rows.map(r=><tr key={r.UserName+r.Contact}><td>{r.UserName}</td><td>{r.Districts}</td><td>{r["Pending MB"]}</td><td>{r["Verified MB"]}</td><td>{r["Rejected MB"]}</td><td>{r["Pending HS100"]}</td><td>{r["Verified HS100"]}</td><td>{r["Rejected HS100"]}</td></tr>)}{!rows.length&&!loading&&<tr><td colSpan="8" className="empty-row">No verification users found.</td></tr>}</tbody></table></div></section></OfficialShell>;
}
